### ISSUE TITLE
I can't find pycocotools.ytvos

### ISSUE THREAD

**Issue by czj942650673** [hustvl/TeViT#1]
Traceback (most recent call last):
  File "./tools/train.py", line 17, in <module>
    from mmdet.apis import init_random_seed, set_random_seed, train_detector
  File "/home/hss/TeViT-main/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/hss/TeViT-main/mmdet/apis/inference.py", line 12, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/home/hss/TeViT-main/mmdet/datasets/__init__.py", line 18, in <module>
Traceback (most recent call last):
  File "./tools/train.py", line 17, in <module>
    from .youtubevis import YoutubeVISDataset
  File "/home/hss/TeViT-main/mmdet/datasets/youtubevis.py", line 9, in <module>
    from pycocotools.ytvos import YTVOS
ModuleNotFoundError: No module named 'pycocotools.ytvos'
    from mmdet.apis import init_random_seed, set_random_seed, train_detector
  File "/home/hss/TeViT-main/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/hss/TeViT-main/mmdet/apis/inference.py", line 12, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/home/hss/TeViT-main/mmdet/datasets/__init__.py", line 18, in <module>
    from .youtubevis import YoutubeVISDataset
  File "/home/hss/TeViT-main/mmdet/datasets/youtubevis.py", line 9, in <module>
    from pycocotools.ytvos import YTVOS

**Comment by vealocia** [comment]
Hi, @czj942650673 ! Thanks for your interests in our work.
Please install ```cocoapi``` from https://github.com/youtubevos/cocoapi and try again.

**Comment by czj942650673** [comment]
thanks！

**Comment by PoojanPanchal** [comment]
> Hi, @czj942650673 ! Thanks for your interests in our work. Please install `cocoapi` from https://github.com/youtubevos/cocoapi and try again.

Hi @vealocia 
I am facing the same issue and when I am trying to install cocapi, it is giving following error
`running build_ext
skipping 'pycocotools\_mask.c' Cython extension (up-to-date)
building 'pycocotools._mask' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\pooja\anaconda3\lib\site-packages\numpy\core\include -I../common -IC:\Users\pooja\anaconda3\include -IC:\Users\pooja\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.8\Release\../common/maskApi.obj -Wno-cpp -Wno-unused-function -std=c99
cl : Command line error D8021 : invalid numeric argument '/Wno-cpp'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2`

Is there a way to resolve the following issue?

**Comment by vealocia** [comment]
Hi, @PoojanPanchal 
It seems like a error raised by ```Cython``` and ```Numpy```. I guess there are some issues with your python or system environment. So it's hard to give you a clear direction. Maybe you can check your custom work environments.

**Comment by PoojanPanchal** [comment]
Thank you @vealocia!! yeah i think issue is with my work environment. 

I was able to resolve the above issue by directly copying the ytvos.py file into the site-package/pycocotools folder. 
This solution can be found on the following thread - https://github.com/Epiphqny/VisTR/issues/5#issuecomment-819837393
